chore(release): 2.7.0
awslabs/fhir-works-on-aws-deployment pull request #307
Opened 2021-04-30 10:02 UTC by carvantes

It's tricky to automatically generate good release notes for this package since the meaningful changes are in other fwoa components. 

This is a mix of: auto-generated w `standard-version` + copied most relevant notes from other fwoa changelogs + manual changes in formatting/adding a bit more details

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-04-30 10:28 UTC, rsmayda requested changes

2021-04-30 10:28 UTC, rsmayda commented on CHANGELOG.md
> +- [fhir-works-on-aws-routing v3.3.1 -> v3.3.3](https://github.com/awslabs/fhir-works-on-aws-routing/compare/v5.1.1...v5.2.0)
Numbering is off

2021-04-30 15:00 UTC, rsmayda approved these changes

2021-04-30 15:27 UTC, nguyen102 approved these changes

2021-04-30 16:15 UTC, merged

2021-05-26 21:35 UTC, carvantes reviewed
.