feat: emit end to end latency metric from rest-hook Lambda
awslabs/fhir-works-on-aws-deployment pull request #570
Opened 2022-02-17 21:42 UTC by Bingjiling

Issue #, if available:

Description of changes:

* Emit end to end latency metric from rest-hook Lambda

Checklist:

* [ ] Have you successfully deployed to an AWS account with your changes?
* [ ] Have you written new tests for your core changes, as applicable?

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-02-18 00:48 UTC, carvantes requested changes

2022-02-18 00:48 UTC, carvantes commented on src/subscriptions/restHookLambda/restHook.ts
> +import moment from 'moment';
I'd suggest not using `moment`

The difference in milliseconds is easy to calculate using the available Date functions
```
Date.now() - (new Date('2022-02-17T20:33:57.021Z')).getTime()
```

Also, moment is sort of deprecated nowadays: https://github.com/moment/moment/#project-status

2022-02-18 00:48 UTC, carvantes commented on src/subscriptions/restHookLambda/restHook.ts
> +const pushLatencyMetric = metricScope((metrics) => async (messages: SubscriptionNotification[]): Promise<void> => {
nit: rename to something like `recordLatencyMetric` or ``logLatencyMetric``. I think that "push" sounds misleading

2022-02-18 18:03 UTC, Bingjiling commented on src/subscriptions/restHookLambda/restHook.ts
> +import moment from 'moment';
Wow, I didn't know moment is getting deprecated. Will update to Date.

2022-02-18 21:50 UTC, carvantes requested changes

2022-02-18 21:50 UTC, carvantes commented on src/subscriptions/restHookLambda/restHook.ts
> +            Unit.Seconds,
It's almost always better to emit metrics in the smallest unit available. In this case Milliseconds.

When storing milliseconds you can always divide by 1000 on the graphs if you want to see seconds. But storing the metric as seconds destroys the milliseconds information.

2022-02-22 20:33 UTC, carvantes approved these changes

2022-02-22 20:35 UTC, merged